# Generated by Django 6.0.2 on 2026-02-23 14:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_oficial', models.CharField(max_length=300)),
                ('nome_usual', models.CharField(blank=True, max_length=300)),
                ('diretor', models.CharField(blank=True, max_length=200)),
                ('mediador', models.CharField(blank=True, max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=500)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('sistema', 'Sistema'), ('manual', 'Manual')], default='sistema', max_length=20)),
                ('bloco_1', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome_oficial'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_exibicao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mediador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('escola_nome', models.CharField(blank=True, max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediadores', to='core.escola')),
            ],
            options={
                'verbose_name': 'Mediador',
                'verbose_name_plural': 'Mediadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita', 'Visita'), ('reuniao', 'Reunião'), ('feriado', 'Feriado'), ('apresentacao', 'Apresentação'), ('capacitacao', 'Capacitação'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('titulo', models.CharField(max_length=500)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], max_length=20)),
                ('dia_inteiro', models.BooleanField(default=False)),
                ('escola_nome', models.CharField(blank=True, max_length=300)),
                ('local', models.CharField(blank=True, max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('mediador_nome', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('executado', 'Executado'), ('cancelado', 'Cancelado')], default='planejado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.escola')),
                ('mediador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='core.mediador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_nome', models.CharField(blank=True, max_length=300)),
                ('escola_nome_oficial', models.CharField(blank=True, max_length=300)),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('integral', 'Integral')], max_length=20)),
                ('oficina', models.CharField(blank=True, max_length=500)),
                ('observacoes', models.TextField(blank=True)),
                ('contribuicoes', models.TextField(blank=True)),
                ('combinados', models.TextField(blank=True)),
                ('mediador_nome', models.CharField(blank=True, max_length=200)),
                ('articulador_nome', models.CharField(blank=True, max_length=200)),
                ('gestor_nome', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='core.escola')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TurmaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_turma', models.CharField(blank=True, max_length=200)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=200)),
                ('avaliacao', models.CharField(blank=True, max_length=50)),
                ('faixa_etaria', models.CharField(blank=True, max_length=100)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.visita')),
            ],
            options={
                'verbose_name': 'Turma da Visita',
                'verbose_name_plural': 'Turmas das Visitas',
            },
        ),
        migrations.CreateModel(
            name='AnexoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, upload_to='uploads/')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('nome_original', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.visita')),
            ],
            options={
                'verbose_name': 'Anexo de Visita',
                'verbose_name_plural': 'Anexos de Visitas',
            },
        ),
    ]
